{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "control-plane.pvcName" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{ with .Values.persistence.storageClass }}
  storageClassName: {{ . }}
{{ end }}
{{- end }}

