# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

tracing:
  log_level: info
  display_thread_names: true
  display_thread_ids: true

runtime:
  n_cores: 0
  thread_name: "slim-data-plane"
  drain_timeout: 10s

services:
  slim/0:
    node_id: ${env:SLIM_SVC_ID}
    group_name: cluster-a
    dataplane:
      servers:
        - endpoint: "0.0.0.0:46457"
          metadata:
            external_endpoint: "localhost:46457"            
          tls:
            insecure: true

      clients: []
    controller:
      clients:
        - endpoint: "http://127.0.0.1:50052"
          tls:
            insecure: true
