# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

[project]
name = "slim-uniffi-bindings-examples"
version = "0.7.0"
description = "Examples for SLIM UniFFI Python Bindings"
requires-python = ">=3.10"
readme = "README.md"
license = "Apache-2.0"
authors = [
    {name = "AGNTCY Contributors", email = "slim@agntcy.io"}
]

dependencies = [
    "slim-uniffi-bindings",
]

[project.urls]
Repository = "https://github.com/agntcy/slim"
Issues = "https://github.com/agntcy/slim/issues"

[tool.uv.sources]
slim-uniffi-bindings = { path = "..", editable = true }

[tool.uv]
dev-dependencies = []

