{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slim.fullname" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if .Values.slim.overrideConfig }}
    {{- tpl (toYaml .Values.slim.overrideConfig) . | nindent 4 }}
    {{- else }}
    {{- tpl (toYaml .Values.slim.config) . | nindent 4 }}
    {{- end }}
