{{/*
Copyright AGNTCY Contributors (https://github.com/agntcy)
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if eq .Values.slim.daemonset true }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "slim.fullname" . }}
  labels:
    {{- include "slim.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "slim.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.slim.updateStrategy.type | default "RollingUpdate" }}
    {{- if eq (.Values.slim.updateStrategy.type | default "RollingUpdate") "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.slim.updateStrategy.rollingUpdate.maxUnavailable | default 1 }}
    {{- end }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "slim.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slim.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.slim.image.repository }}:{{ .Values.slim.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.slim.image.pullPolicy }}
          command:
            - "/slim"
          args:
            - "--config"
            - "/config.yaml"
          env:
            - name: SLIM_SVC_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP                  
          ports:
            - name: data-plane
              containerPort: {{ .Values.slim.service.data.port }}
              protocol: TCP
              hostPort: {{ .Values.slim.service.data.port }}
            - name: controller
              containerPort: {{ .Values.slim.service.control.port }}
              protocol: TCP
              hostPort: {{ .Values.slim.service.control.port }}
          resources:
            {{- toYaml .Values.slim.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /config.yaml
              subPath: config.yaml
{{- if eq .Values.spire.enabled true }}
            - name: spire-agent-socket
              mountPath: /tmp/spire-agent/public/
              readOnly: true
{{- end }}
{{- with .Values.slim.extraVolumeMounts }}
{{ toYaml . | nindent 12 }}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "slim.fullname" . }}
        {{- with .Values.slim.extraVolumes }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
{{- if eq .Values.spire.enabled true }}
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory
{{- end}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: {{ .Values.slim.hostNetwork | default false }}
      dnsPolicy: {{ .Values.slim.dnsPolicy | default "ClusterFirst" }}
{{- end }}