[workspace]
release_always = true
# do not release packages by default
release = false

# Remove agntcy- from git tag and release names
git_tag_name = "{{ package | replace(from='agntcy-', to='') }}-v{{ version }}"
git_release_name = "{{ package | replace(from='agntcy-', to='') }} v{{ version }}"

[[package]]
name = "agntcy-slim-config"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-datapath"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-service"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-session"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-signal"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-tracing"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-bindings"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-controller"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-auth"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slim-mls"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-protoc-slimrpc-plugin"
publish = true
release = true
changelog_update = true

[[package]]
name = "agntcy-slimctl"
publish = true
release = true
changelog_update = true
