[default]
extend-ignore-re = [
    "(?Rm)^.*(#|//)\\s*spellchecker:disable-line$",
    "(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
]

[files]
# Ignore all changelogs and generated bindings files
extend-exclude = [
    "**/CHANGELOG.md",
    "**/*.pem",
    "**/*.yaml",
    "bindings/go/generated/**",
    "**/*.pbxproj",
    "**/*.pbxproj.bak",
]
