# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

[project]
name = "slim-bindings-examples"
version = "0.1.0"
description = "Example apps using SLIM Rust bindings for Python"
requires-python = ">=3.9"
license = "Apache-2.0"
dependencies = ["slim-bindings>=0.3.6", "pyjwt>=2.10.1", "click>=8.1.8"]

[tool.uv.sources]
slim-bindings = { workspace = true }

[project.scripts]
examples = "slim_bindings_examples:main"
slim = "slim_bindings_examples:slim_main"
anycast = "slim_bindings_examples:anycast_main"
unicast = "slim_bindings_examples:unicast_main"
multicast = "slim_bindings_examples:multicast_main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/slim_bindings_examples"]
