northbound:
  httpHost: localhost
  httpPort: 50051

southbound:
  httpHost: localhost
  httpPort: 50052

reconciler:
  maxRequeues: 15
  maxNumOfParallelReconciles: 1000

logging:
  level: DEBUG

database:
  # By default, Controller use in-memory database, set filePath to use a file-based SQLite database
  #filePath: db/controlplane.db


