northbound:
  httpHost: localhost
  httpPort: 50051

southbound:
  httpHost: localhost
  httpPort: 50052
  tls:
    useSpiffe: true
  spire:
    socketPath: "unix:///tmp/spire-agent/public/api.sock"

reconcilerThreads: 3

logging:
  level: DEBUG


