northbound:
  httpHost: localhost
  httpPort: 50051

southbound:
  httpHost: localhost
  httpPort: 50052

reconciler:
  maxRequeues: 15
  maxNumOfParallelReconciles: 1000

logging:
  level: DEBUG

database:
  filePath: db/controlplane.db


