northbound:
  httpHost: localhost
  httpPort: 50051

southbound:
  httpHost: localhost
  httpPort: 50052
  tls:
    certFile: "/certs/tls.crt"
    keyFile: "/certs/tls.key"
    caFile: "//certs/ca_bundle.pem"

reconcilerThreads: 3

logging:
  level: DEBUG
