# Copyright AGNTCY Contributors (https://github.com/agntcy)
# SPDX-License-Identifier: Apache-2.0

---
name: ci-test-and-build-control-plane

on:
  push:
    paths:
      - 'control-plane/**'
    branches:
      - main
  pull_request:
    paths:
      - 'control-plane/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read
  actions: write

jobs:
  control-plane-build-and-test:
    name: Control plane - build & test
    uses: ./.github/workflows/reusable-go-build-and-test.yaml

    with:
      go-version: 1.25.5
      working-directory: ./control-plane

  control-plane-docker-build:
    name: Build control plane docker image
    uses: ./.github/workflows/reusable-docker-build-push.yaml
    with:
      bake-targets: control-plane
      image-tag: ${{ github.sha }}
